this is an edit taking place on the server.  it represents when josh or brad did something i need to pull down.  hope this works out...

ok, so i did this by using git pull, lets try pushing this up to the repo, then using fetch instead and rebasing.  here goes nothin...
